spring:
  application:
    name: underlive

  datasource:
    url: jdbc:mysql://localhost:3306/underlive2
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8081