spring:
  application:
    name: underlive

  datasource:
    url: jdbc:postgresql://localhost:5432/underlive
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
    database: postgresql

server:
  port: 8081