name: Gradle CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

            - name: Build with Gradle Wrapper
              run: ./gradlew build

    ktlint:
        name: Check Code Quality
        runs-on: ubuntu-latest
        steps:
            -   name: Clone repo
                uses: actions/checkout@master
                with:
                    fetch-depth: 1
            -   name: ktlint
                uses: ScaCap/action-ktlint@master
                with:
                    github_token: ${{ secrets.GH_TOKEN }}
                    reporter: github-pr-review

